import clsx from 'clsx'
import type { Metadata } from 'next'
import { MontserratFont, DuskDemon } from '@/common/fonts'
import Footer from '@/components/Footer'
import Header from '@/components/Header'
import '@/styles/globals.scss'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="uk" className={clsx(MontserratFont.variable, DuskDemon.variable)}>
      <body>
        <style
          dangerouslySetInnerHTML={{
            __html: `
          button, textarea, input {
            font-family: ${MontserratFont.style.fontFamily}
          }
            `,
          }}
        />
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
