import { DuskDemon, MontserratFont } from '@/common/fonts'
import clsx from 'clsx'
import '@/styles/globals.scss'
import Providers from '@/store/provider'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={clsx(MontserratFont.variable, DuskDemon.variable)}>
    <body>
    <style
      dangerouslySetInnerHTML={{
        __html: `
          button, textarea, input {
            font-family: ${MontserratFont.style.fontFamily}
          }
            `,
      }}
    />
    <Providers>
      <main>{children}</main>
    </Providers>
    </body>
    </html>
  )
}
